### ISSUE TITLE
Команда для обнуления бибы себе/другим людям

### ISSUE THREAD

**Issue by YaMaZZZim** [C0deRang3rs/bibabot#56]

**Comment by YaMaZZZim** [comment]
Нужно для тестов на деве чтоб не дропать БД каждый раз.

**Comment by howHighUR** [comment]
Добавил 3 команды:
- `/set_biba *size* @*username*` (без юзернейма сетит автору сообщения)
- `/remove_biba @*username*` (без юзернейма удаляет бибу автора сообщения)
- `/trigger_daily`

**Comment by YaMaZZZim** [comment]
Проверенно на деве.
