### ISSUE TITLE
Реакция бота на ролл максимальной/минимальной бибы

### ISSUE THREAD

**Issue by YaMaZZZim** [C0deRang3rs/bibabot#68]
Что-то типа:
- "Микробиба", "Даже у даши больше", "Почти как у владика в холодной водичке"
- "БИБЗИЛЛА", "Дорогу здоровяку", "Внук Деда Максима"

**Comment by YaMaZZZim** [comment]
Можно сделать чтоб он реагировал не только на максимальный/минимальный результат но и на ближайшие 2. Т.е. 0-3 см и 33-35

**Comment by YaMaZZZim** [comment]
Фича работает. Подумай над пунктуацией и порядком фраз. Предлагаю добавить несколько фраз с рандомизацией.

**Comment by howHighUR** [comment]
Добавил точку, остальное надо перенести в отдельную задачу. Пока релизим как есть

**Comment by YaMaZZZim** [comment]
Проверенно на деве. Рандомизацию сделаю в новую задачу.
