### ISSUE TITLE
Пособие по микробибности

### ISSUE THREAD

**Issue by YaMaZZZim** [C0deRang3rs/bibabot#72]
Давать попособие по ~~инвалидности~~ микробибности ~20 бибакоинов или что-то другое тем у кого выпала биба меньше 5см.

**Comment by YaMaZZZim** [comment]
Все работает. Можно добавить ограничение по одному пособию в день. Ну или можно не добавлять.

**Comment by howHighUR** [comment]
Не думаю. 1 ролл + рероллы, и если тебе постоянно падает маленькая биба, то с реролла это х2 обидно
