### ISSUE TITLE
Мем месяца + удаление старых записей с редиса

### ISSUE THREAD

**Issue by muuuzmich** [C0deRang3rs/bibabot#92]

**Comment by howHighUR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Очистка базы от устаревших мемов](https://trello.com/c/uyOuMb64/12-%D0%BE%D1%87%D0%B8%D1%81%D1%82%D0%BA%D0%B0-%D0%B1%D0%B0%D0%B7%D1%8B-%D0%BE%D1%82-%D1%83%D1%81%D1%82%D0%B0%D1%80%D0%B5%D0%B2%D1%88%D0%B8%D1%85-%D0%BC%D0%B5%D0%BC%D0%BE%D0%B2)
