### ISSUE TITLE
Удалять оценку мемов при удалении самого мема

### ISSUE THREAD

**Issue by muuuzmich** [C0deRang3rs/bibabot#93]

**Comment by howHighUR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Удалять оценку мема при удалении](https://trello.com/c/kp9WoZsy/1-%D1%83%D0%B4%D0%B0%D0%BB%D1%8F%D1%82%D1%8C-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D1%83-%D0%BC%D0%B5%D0%BC%D0%B0-%D0%BF%D1%80%D0%B8-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8)
