### ISSUE TITLE
Возможность добавлять картинки в стикерпак

### ISSUE THREAD

**Issue by muuuzmich** [C0deRang3rs/bibabot#95]

**Comment by howHighUR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Добавление картинок в стикеры](https://trello.com/c/6KNS8GIa/11-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BE%D0%BA-%D0%B2-%D1%81%D1%82%D0%B8%D0%BA%D0%B5%D1%80%D1%8B)
